# Environment Settings
gpu_id: '0'
worker: 16
seed: 2020
checkpoint_dir: 'saved/'
log_wandb: True
wandb_project: 'ncf-epm'

# dataset config : General Recommendation
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
load_col:
    inter: [user_id, item_id]

# model config
mf_embedding_size: 32
mlp_embedding_size: 32
mlp_hidden_size: [64, 32, 16, 8]
dropout_prob: 0.1
mf_train: True
mlp_train: True
use_pretrain: False
mf_pretrain_path: None
mlp_pretrain_path: None

# Training and evaluation config
epochs: 600
learner: adam
learning_rate: 0.001
train_batch_size: 4096
eval_batch_size: 4096
stopping_step: 10
train_neg_sample_args:
    distribution: uniform
    sample_num: 1
    alpha: 1.0
    dynamic: False
    candidate_num: 0
eval_args:
    group_by: user
    order: RO
    split: {'RS': [0.8,0.1,0.1]}
    mode: uni100
metrics: ['AUC', 'MAE', 'RMSE', 'LogLoss']
topk: 10
valid_metric: RMSE
metric_decimal_place: 4
